#!/usr/bin/env ruby
# frozen_string_literal: true
require 'pastel'
@pastel = Pastel.new

lib_path = File.expand_path('../lib', __dir__)
$:.unshift(lib_path) if !$:.include?(lib_path)
require 'auditrb/cli'

def show_logo()
  require 'tty-font'
  font = TTY::Font.new(:doom)
  puts @pastel.green(font.write("Auditrb"))
end

def print_err(s)
  puts @pastel.red.bold(s)
end

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  show_logo()
  Auditrb::CLI.start
rescue Auditrb::CLI::Error => err
  print_err "ERROR: #{err.message}"
  exit 1
end


